Feature Комментарии пользователей
alexkiktev/java-explore-with-me pull request #5
Opened 2023-05-07 16:08 UTC by alexkiktev

2023-05-07 19:43 UTC, Frilock requested changes
Добрый вечер, Алексей, сильная работа, мне все очень понравилось, и я хотел сразу все принять, но потом обратил внимание на несколько моментов в коде. Написал Вам о них, поправьте или напишите мне, если с чем то не согласны.

2023-05-07 19:43 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        getUser(userId);
Мне не нравится название данного метода, поскольку Вы по сути им проверяете наличие пользователя в БД, логичнее назвать метод checkUserExistById или как то так, а то по сути Ваш метод возвращает пользователя а вы его не используете

2023-05-07 19:43 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        if (!comment.getStatus().equals(StatusComment.PENDING)) {
Писал уже, правильнее сравнивать енамы через стандартные операторы != и ==, иначе будет варнинг от Сонара

2023-05-07 19:43 UTC, Frilock commented on ewm-main/src/main/resources/schema.sql
> +    status VARCHAR(10) NOT NULL,
Данный размер укажите тогда в аннотации column

2023-05-07 19:43 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
На мой взгляд, над частью методов в данном классе нужна транзакция

2023-05-08 05:45 UTC, alexkiktev commented on ewm-main/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        getUser(userId);
Иван, согласен, сделал отдельные методы для получения объекта и проверки наличия для Comment, User, Event.

2023-05-08 05:46 UTC, alexkiktev commented on ewm-main/src/main/resources/schema.sql
> +    status VARCHAR(10) NOT NULL,
Исправил

2023-05-08 05:47 UTC, alexkiktev commented on ewm-main/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
Согласен, упустил. Сделал по аналогии с другими классами сервисного слоя.

2023-05-08 05:53 UTC, alexkiktev commented on ewm-main/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        if (!comment.getStatus().equals(StatusComment.PENDING)) {
Точно, спасибо, исправил.

2023-05-08 17:05 UTC, Frilock approved these changes
Работу принял, но не очень понятно зачем убираете дефолтную изоляцию у транзакций. На мой взгляд, достаточно стандартной.

2023-05-10 10:43 UTC, merged